name: advanced_flutter_tutorial
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0
  retrofit: ^4.6.0
  analyzer: ^7.7.1
  dio: ^5.8.0+1
  json_serializable: ^6.9.5
  retrofit_generator: ^9.6.0
  build_runner: ^2.4.15
  dartz: ^0.10.1
  internet_connection_checker: ^3.0.1
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.5.3
  freezed: ^3.0.6
  get_it: ^8.2.0
  lottie: ^3.3.1
  easy_localization: ^3.0.8
  rxdart: ^0.28.0
  image_picker: ^0.8.4+11
  flutter_phoenix: ^1.0.0
  country_code_picker: ^3.4.0
  carousel_slider: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true

  assets:
     - assets/images/splash_logo.png
     - assets/images/onboarding_logo1.svg
     - assets/images/onboarding_logo2.svg
     - assets/images/onboarding_logo3.svg
     - assets/images/onboarding_logo4.svg
     - assets/images/hollow_circle_ic.svg
     - assets/images/solid_circle_ic.svg
     - assets/images/left_arrow_ic.svg
     - assets/images/right_arrow_ic.svg
     - assets/images/photo-camera.svg
     - assets/images/change_lang_ic.svg
     - assets/images/contact_us_ic.svg
     - assets/images/invite_friends_ic.svg
     - assets/images/logout_ic.svg
     - assets/images/right_arrow_settings_ic.svg
     - assets/json/loading.json
     - assets/json/error.json
     - assets/json/empty.json
     - assets/json/success.json
     - assets/translations/ar-SA.json
     - assets/translations/en-US.json



  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
 